### ISSUE TITLE
error when the word "order" is supplied to Posgtres parser, in many cases

### ISSUE THREAD

**Issue by dlparker** [AGHerwig/searchstringparser#1]
Also some other words starting with "or" such as "orange" and "orbit". 
Same behavior on Linux (Mint 18.3) and Mac OS (Sierra).

using:

PostgreSQLTextSearchParser().parser(terms)

where terms:
This works:
foo order
These give errors:
foo & order
foo or order 
foo | order
order foo

The errors look like this (in django trace):

![image](https://user-images.githubusercontent.com/660124/45599753-e6abb800-b9b6-11e8-87c0-13073f7fbb16.png)

**Comment by dlparker** [comment]
Wondering if other operator words have the same problem, I tried 
andrew foo
and got the same error, so it appears to be false positives finding operators generally.

**Comment by Midnighter** [comment]
Thank you for the report, I didn't actually know that anyone is using this package :wink: I haven't touched the code in years so the support I can give is a bit shaky. It seems like the defined tokens are a bit too greedy.

**Comment by Midnighter** [comment]
Hi @dlparker, I have fixed the issue. I just need to update the testing pipeline and then I'll make a new release.

**Comment by Midnighter** [comment]
And I have just released version 0.3.0 on PyPI, please try it out with `pip install -U searchstringparser`.
